### ISSUE TITLE
Isometric Game crashes in web browser

### ISSUE THREAD

**Issue by krasi-sabyata** [godotengine/godot-demo-projects#1093]
**Which demo project is affected:** `2d/isometric`

**OS/device including version:**
Browser: Chrome Version 126.0.6478.183 (Official Build) (arm64)
OS: Mac OS Sonoma 14.5

**Issue description:** When opening the Isometric Game demo in browser, loading bar appears for about a second and then the screen shows `null function or function signature mismatch`. 

**Screenshots of issue:**
<img width="1512" alt="Screenshot 2024-07-26 at 11 05 57 PM" src="https://github.com/user-attachments/assets/435669d5-0615-4e2a-a3c8-53b0af7ec6aa">

**Comment by krasi-sabyata** [comment]
console log below
```
index.js:339 Godot Engine v3.3.3.stable.official.b973f997f - https://godotengine.org
index.js:9 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
init @ index.js:9
index.js:9 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
create @ index.js:9
index.js:339 OpenGL ES 2.0 Renderer: WebKit WebGL
index.js:339 OpenGL ES Batching: ON
index.js:339  
index.js:354 **ERROR**: Condition "!ti" is true. Returned: 0L
onPrintError @ index.js:354
index.js:354    At: core/class_db.cpp:549:instance() - Condition "!ti" is true. Returned: 0L
onPrintError @ index.js:354
index.js:354 **ERROR**: res://player/goblin.tscn:10 - Parse Error: Can't create sub resource of type: GradientTexture2D
onPrintError @ index.js:354
index.js:354    At: scene/resources/resource_format_text.cpp:499:poll() - res://player/goblin.tscn:10 - Parse Error: Can't create sub resource of type: GradientTexture2D
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "err != OK" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354    At: core/io/resource_loader.cpp:212:load() - Condition "err != OK" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "found" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354    At: core/io/resource_loader.cpp:283:_load() - Condition "found" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "!ti" is true. Returned: 0L
onPrintError @ index.js:354
index.js:354    At: core/class_db.cpp:549:instance() - Condition "!ti" is true. Returned: 0L
onPrintError @ index.js:354
index.js:354 **ERROR**: res://decorations/candle.tscn:37 - Parse Error: Can't create sub resource of type: GradientTexture2D
onPrintError @ index.js:354
index.js:354    At: scene/resources/resource_format_text.cpp:499:poll() - res://decorations/candle.tscn:37 - Parse Error: Can't create sub resource of type: GradientTexture2D
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "err != OK" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354    At: core/io/resource_loader.cpp:212:load() - Condition "err != OK" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "found" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354    At: core/io/resource_loader.cpp:283:_load() - Condition "found" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "!ti" is true. Returned: 0L
onPrintError @ index.js:354
index.js:354    At: core/class_db.cpp:549:instance() - Condition "!ti" is true. Returned: 0L
onPrintError @ index.js:354
index.js:354 **ERROR**: res://dungeon.tscn:38 - Parse Error: Can't create sub resource of type: GradientTexture2D
onPrintError @ index.js:354
index.js:354    At: scene/resources/resource_format_text.cpp:499:poll() - res://dungeon.tscn:38 - Parse Error: Can't create sub resource of type: GradientTexture2D
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "err != OK" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354    At: core/io/resource_loader.cpp:212:load() - Condition "err != OK" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "found" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354    At: core/io/resource_loader.cpp:283:_load() - Condition "found" is true. Returned: RES()
onPrintError @ index.js:354
index.js:354 **ERROR**: Condition "!scene" is true. Returned: false
onPrintError @ index.js:354
index.js:354    At: main/main.cpp:1961:start() - Condition "!scene" is true. Returned: false
onPrintError @ index.js:354
index.js:354 exception thrown: RuntimeError: null function or function signature mismatch,RuntimeError: null function or function signature mismatch
    at wasm://wasm/03050c82:wasm-function[16700]:0x2cdde4
    at wasm://wasm/03050c82:wasm-function[27651]:0x4cbaca
    at Module._main (https://godotengine.github.io/godot-demo-projects/2d/isometric/index.js:9:331600)
    at Object.callMain (https://godotengine.github.io/godot-demo-projects/2d/isometric/index.js:9:336512)
    at https://godotengine.github.io/godot-demo-projects/2d/isometric/index.js:684:28
    at new Promise (<anonymous>)
    at https://godotengine.github.io/godot-demo-projects/2d/isometric/index.js:679:14
onPrintError @ index.js:354
isometric/:212 null function or function signature mismatch
displayFailureNotice @ isometric/:212
```

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-demo-projects/issues/786.
